/* CWS Planning - BWS/Bouwplanning A3 print renderer, single full-page SVG, no popups (V140) */
(function(){
  "use strict";
  const MARKER="CWS_BWS_PRINT_A3_RENDERER_V140";
  const SCRIPT_ID="cwsBwsPrintA3RendererScript";
  const SCRIPT_SRC="/js/core/gantt_print_a3_bouwplanning.js?v=140";
  if(window.__CWS_BWS_PRINT_A3_RENDERER__===MARKER) return;
  window.__CWS_BWS_PRINT_A3_RENDERER__=MARKER;
  try{document.documentElement.dataset.cwsBwsPrintA3Renderer=MARKER;}catch(_){}

  const COLORS={c1:"#2f6fbd",c2:"#00d169",c3:"#f59e0b",c4:"#dc2626",c5:"#8b5cf6",c6:"#14b8a6",c7:"#f97316",c8:"#22c55e",c9:"#1e3a8a",c10:"#38bdf8",c11:"#06b6d4",c12:"#ec4899",c13:"#db2777",c14:"#4f46e5",c15:"#92400e",c16:"#84cc16",c17:"#166534",c18:"#991b1b",c19:"#6b7280",c20:"#111827"};
  const LEG=["BWS Bouw","Dak- en wandmontage","Staalbouwer","Buitenkozijnen","Installateur W","Dakdekker","Grondwerk/infra","Betonvloer","Uithardingstijd","Trapleverancier","OH-deuren","Dekvloeren"];
  const LEG_COL=["#0b71bd","#00d169","#302e6e","#8b35c9","#168fb0","#f28c00","#b57a28","#ce2525","#ffffff","#9e2a2a","#00b050","#ffff00"];
  const MS=["Januari","Februari","Maart","April","Mei","Juni","Juli","Augustus","September","Oktober","November","December"], DS=["zo","ma","di","wo","do","vr","za"];
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const pad=n=>String(n).padStart(2,"0"), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function dt(v){if(v instanceof Date&&isFinite(v))return new Date(Date.UTC(v.getUTCFullYear(),v.getUTCMonth(),v.getUTCDate())); if(!v)return null; const s=String(v).slice(0,10); let m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/); if(m)return new Date(Date.UTC(+m[1],+m[2]-1,+m[3])); m=s.match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/); return m?new Date(Date.UTC(+m[3],+m[2]-1,+m[1])):null;}
  function iso(v){const d=dt(v); return d?`${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`:"";}
  function nl(v){const d=dt(v); return d?`${pad(d.getUTCDate())}-${pad(d.getUTCMonth()+1)}-${d.getUTCFullYear()}`:"—";}
  function add(v,n){const d=dt(v)||new Date(); d.setUTCDate(d.getUTCDate()+Number(n||0)); return iso(d);}
  function dif(a,b){const da=dt(a),db=dt(b); return da&&db?Math.round((db-da)/86400000):0;}
  function weekStart(v){const d=dt(v)||new Date(),w=d.getUTCDay()||7; d.setUTCDate(d.getUTCDate()-w+1); return iso(d);}
  function weekEnd(v){return add(weekStart(v),6);}
  function wk(v){const d=dt(v)||new Date(),x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())); const day=x.getUTCDay()||7; x.setUTCDate(x.getUTCDate()+4-day); const y=new Date(Date.UTC(x.getUTCFullYear(),0,1)); return {year:x.getUTCFullYear(),week:Math.ceil((((x-y)/86400000)+1)/7)};}
  function cws(){try{return window.CWS||(window.parent&&window.parent!==window&&window.parent.CWS)||null;}catch(_){return window.CWS||null;}}
  function state(){return cws()?.getState?.()||{};}
  function clone(x){try{return JSON.parse(JSON.stringify(x??null));}catch(_){return x;}}
  function projects(s){const by=s?.projects?.byId||{}, order=Array.isArray(s?.projects?.order)?s.projects.order:Object.keys(by); return order.map(id=>by[id]).filter(Boolean);}
  function currentProjectId(s){const ps=projects(s), ids=new Set(ps.map(p=>String(p.id||""))); const cand=[document.getElementById("projectSel")?.value,document.getElementById("mobileProjectSel")?.value,s?.ui?.globalSearchTarget?.projectId,s?.ganttV2?.ui?.projectId,ps.find(p=>String(p.status||"").toLowerCase()!=="gereed")?.id,ps[0]?.id].filter(Boolean).map(String); return cand.find(x=>ids.has(x))||ps[0]?.id||null;}
  function title(p){return p?.name||p?.title||p?.omschrijving||p?.description||"Project";}
  function client(p){return p?.client||p?.opdrachtgever||p?.customer||p?.klant||"";}
  function pno(p){return p?.nr||p?.code||p?.number||p?.projectnummer||p?.id||"—";}
  function logo(s){return s?.company?.logo?.dataUrl||cws()?.getCompanyLogo?.()||"";}
  function resources(s){return s?.resources?.byId||{};}
  function model(projectId,s){let m=null; try{m=cws()?.gantt?.getProjectGantt?.(projectId);}catch(_){} m=m||s?.ganttV2?.byProject?.[projectId]||{}; m=clone(m)||{}; m.rows=Array.isArray(m.rows)?m.rows.filter(Boolean):[]; m.sched=m.sched&&typeof m.sched==="object"?m.sched:{}; return m;}
  function isSummary(r){const t=String(r?.type||r?.kind||"").toLowerCase(); return t==="summary"||t==="phase"||t==="fase"||r?.summary===true||r?.isPhase===true;}
  function level(r){const n=Number(r?.level??r?.indent??0); return isFinite(n)?Math.max(0,n):0;}
  function clean(a,b){a=iso(a); b=iso(b); if(a&&!b)b=a; if(b&&!a)a=b; if(a&&b&&dif(a,b)<0){const t=a;a=b;b=t;} return a&&b?{start:a,end:b}:null;}
  function findRowEl(sel,id){return Array.from(document.querySelectorAll(sel)).find(el=>String(el?.dataset?.id||"")===String(id));}
  function domSchedule(r){const id=String(r?.id||""); const bar=findRowEl(".bar[data-id]",id); let sc=clean(bar?.dataset?.start,bar?.dataset?.end); if(sc)return sc; const tr=findRowEl("#tableRows tr[data-id]",id); const a=tr?.querySelector?.('input[data-k="start"],input.dateinput[data-k="start"],input[type="date"][data-k="start"]')?.value; const b=tr?.querySelector?.('input[data-k="end"],input.dateinput[data-k="end"],input[type="date"][data-k="end"]')?.value; return clean(a,b)||clean(r?.start||r?.startDate||r?.begin,r?.end||r?.endDate||r?.einde);}
  function rawSchedule(r,m){const sc=m?.sched?.[r?.id]||{}; return clean(sc.start||sc.startDate||r?.start||r?.startDate||r?.begin,sc.end||sc.endDate||r?.end||r?.endDate||r?.einde)||domSchedule(r)||{};}
  function blockEnd(rows,i){const base=level(rows[i]); let e=i; for(let j=i+1;j<rows.length;j++){if(rows[j]?.parent&&rows[i]?.id&&String(rows[j].parent)===String(rows[i].id)){e=j;continue;} if(level(rows[j])<=base)break; e=j;} return e;}
  function rebuildSummaries(rows,map){for(let i=rows.length-1;i>=0;i--){const r=rows[i]; if(!isSummary(r))continue; const kids=rows.slice(i+1,blockEnd(rows,i)+1).map(x=>map.get(x.id)).filter(x=>x?.start&&x?.end); if(kids.length)map.set(r.id,{start:kids.map(x=>x.start).sort()[0],end:kids.map(x=>x.end).sort().at(-1)});}}
  function scheduleMap(rows,m){const map=new Map(); rows.forEach(r=>{const sc=rawSchedule(r,m); if(sc?.start&&sc?.end)map.set(r.id,sc);}); rebuildSummaries(rows,map); return map;}
  function hydrate(rows,map,p){let cursor=iso(p?.startDate||p?.start||p?.date)||iso(new Date()); rows.forEach((r,i)=>{if(map.get(r.id)?.start&&map.get(r.id)?.end)return; const dom=domSchedule(r); if(dom?.start&&dom?.end){map.set(r.id,dom); return;} if(isSummary(r))return; const dur=Math.max(1,Number(r?.duration||r?.days||r?.duur||r?.workdays||5)||5); const start=add(cursor,i===0?0:1), end=add(start,dur-1); map.set(r.id,{start,end,generated:true}); cursor=end;}); rebuildSummaries(rows,map);}
  function bouw(r,s){const res=r?.resourceId?resources(s)[r.resourceId]:null; return r?.bouwkundig||r?.discipline||r?.department||r?.dept||r?.afdeling||res?.dept||r?.resource||r?.resourceId||"—";}
  function resource(r,s){const res=r?.resourceId?resources(s)[r.resourceId]:null; return res?.name||r?.resourceName||r?.resource||r?.resourceId||bouw(r,s);}
  function color(r,i){const label=String(resource(r,state())||"").toLowerCase(); const ix=LEG.findIndex(x=>label.includes(x.toLowerCase())); if(ix>=0)return LEG_COL[ix]; const v=String(r?.colorKey||r?.color||"").trim(); return /^#[0-9a-f]{3,8}$/i.test(v)?v:(COLORS[v]||COLORS[`c${(i%12)+1}`]||COLORS.c1);}
  function nonwork(s,d){const x=dt(d); if(!x)return false; const wd=x.getUTCDay()===0?7:x.getUTCDay(), cal=s?.settings?.calendar||{}, ov=cal?.overrides?.[d]; if(typeof ov==="boolean")return ov; if(wd===6||wd===7)return true; if(cal?.workweek&&cal.workweek[wd]===false)return true; const hit=(Array.isArray(s?.settings?.tables?.calendar)?s.settings.tables.calendar:[]).find(r=>String(r?.date||"").slice(0,10)===String(d)); return !!(hit&&hit.isWorking===false);}
  function range(rows,map,s,pid){const p=s?.projects?.byId?.[pid]||{}, dates=[]; rows.forEach(r=>{const x=map.get(r.id); if(x?.start)dates.push(x.start); if(x?.end)dates.push(x.end);}); let a=dates.length?dates.sort()[0]:iso(p.startDate||p.start||new Date()), b=dates.length?dates.sort().at(-1):add(a,42); a=weekStart(add(a,-7)); b=weekEnd(add(b,7)); if(dif(a,b)+1>190)b=add(a,189); const days=[]; for(let d=a,g=0;dif(d,b)<=0&&g<220;d=add(d,1),g++)days.push(d); return {start:a,end:b,days};}
  function data(){const s=state(), pid=currentProjectId(s), p=s?.projects?.byId?.[pid]||projects(s)[0]||{}, m=model(pid,s), realRows=m.rows.length?m.rows:[{id:"empty",name:"Geen Gantt-regels beschikbaar",type:"summary",department:"—",colorKey:"c20"}], map=scheduleMap(realRows,m); hydrate(realRows,map,p); const rg=range(realRows,map,s,pid); return {s,pid,p,m,realRows,rows:realRows.map((r,i)=>({r,i,no:i+1,sc:map.get(r.id)||rawSchedule(r,m)})),range:rg,days:rg.days};}
  function tx(x,y,t,size=2.1,weight=700,anchor="middle",extra=""){return `<text x="${x}" y="${y}" font-size="${size}" font-weight="${weight}" text-anchor="${anchor}" dominant-baseline="middle" font-family="Arial,Helvetica,sans-serif" ${extra}>${esc(t)}</text>`;}
  function line(x1,y1,x2,y2,w=.18,c="#000",dash=""){return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${c}" stroke-width="${w}"${dash?` stroke-dasharray="${dash}"`:""}/>`;}
  function rect(x,y,w,h,fill="#fff",stroke="#000",sw=.18,extra=""){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${fill}" stroke="${stroke}" stroke-width="${sw}" ${extra}/>`;}
  function segments(days,type){const key=d=>{const x=dt(d); if(type==="year")return String(x.getUTCFullYear()); if(type==="month")return `${x.getUTCFullYear()}-${pad(x.getUTCMonth()+1)}`; if(type==="week"){const w=wk(x); return `${w.year}-W${pad(w.week)}`;} return d;}; const lab=k=>{if(type==="year")return k; if(type==="month"){const [y,m]=k.split("-");return MS[+m-1];} if(type==="week")return String(+(k.match(/W(\d+)$/)||[])[1]||""); const x=dt(k); return `${pad(x.getUTCDate())}`;}; const out=[]; days.forEach(d=>{const k=key(d), last=out.at(-1); if(last&&last.key===k)last.n++; else out.push({key:k,n:1,label:lab(k)});}); return out;}
  function headerSvg(d,W,M,headH){const p=d.p, metaX=W-M-84, y=M; let s=rect(M,y,W-2*M,headH,"#fff","#000",.35); s+=rect(M,y,78,headH,"#fff","#000",.25); const l=logo(d.s); if(l)s+=`<image href="${esc(l)}" x="${M+6}" y="${y+4}" width="64" height="14" preserveAspectRatio="xMidYMid meet"/>`; else{s+=rect(M+6,y+4,64,14,"#ffd92f","none",0); s+=tx(M+38,y+10,"TASCHE",5.5,900); s+=tx(M+38,y+15,"STAALBOUW",2.4,800);} s+=tx(W/2,y+8,title(p),3.2,900); s+=tx(W/2,y+13,`Opdrachtg.: ${client(p)||"—"}`,2.35,900); s+=tx(W/2,y+17,`Bouwplanning · bereik ${nl(d.range.start)} t/m ${nl(d.range.end)}`,1.55,700); const rows=[["Project nr.:",pno(p)],["Opdrachtg.:",client(p)||"—"],["Omschrijving:",p.omschrijving||p.description||title(p)],["Projectleider:",p.projectleider||p.projectLead||d.s?.user?.name||"—"],["Plotdatum:",new Date().toLocaleDateString("nl-NL")],["Revisienr.:",p.revision||"—"],["Revisiedatum:",p.revisionDate?nl(p.revisionDate):"—"]]; const rh=headH/rows.length; rows.forEach((r,i)=>{s+=rect(metaX,y+i*rh,28,rh,"#fff","#000",.16); s+=rect(metaX+28,y+i*rh,56,rh,"#fff","#000",.16); s+=tx(metaX+1.4,y+i*rh+rh/2,r[0],1.25,900,"start"); s+=tx(metaX+30,y+i*rh+rh/2,r[1],1.25,700,"start");}); return s;}
  function drawCalendar(d,x,y,w,h,top){const order=top?["year","month","date","week"]:["week","date","month","year"], hs=top?[4.5,5,4.5,4.5]:[4.5,4.5,5,4.5]; let s="", yy=y, dayW=w/d.days.length; order.forEach((type,ri)=>{const rh=hs[ri]; if(type==="date"){d.days.forEach((day,i)=>{const xx=x+i*dayW, weekend=nonwork(d.s,day); s+=rect(xx,yy,dayW,rh,weekend?"#d9d9d9":"#fff","#333",.08); s+=tx(xx+dayW/2,yy+rh/2,pad(dt(day).getUTCDate()),1.2,800);});}else{let xx=x; segments(d.days,type).forEach(seg=>{const ww=seg.n*dayW; s+=rect(xx,yy,ww,rh,"#fff","#111",.13); s+=tx(xx+ww/2,yy+rh/2,seg.label,type==="week"?1.25:1.55,900); xx+=ww;});} yy+=rh;}); return s;}
  function fullSvg(d){const W=408,H=285,M=3.5,headH=22,legendH=14,boardY=M+headH,boardW=W-2*M,leftW=108,chartX=M+leftW,chartW=boardW-leftW,topCalH=18.5,bottomCalH=18.5,bodyY=boardY+topCalH,legendY=H-M-legendH,botCalY=legendY-bottomCalH,bodyH=botCalY-bodyY,displayN=Math.max(42,d.rows.length),rowH=bodyH/displayN,dayW=chartW/d.days.length; let s=`<svg xmlns="http://www.w3.org/2000/svg" width="408mm" height="285mm" viewBox="0 0 408 285" shape-rendering="crispEdges">`; s+=rect(M,M,W-2*M,H-2*M,"#fff","#000",.55); s+=headerSvg(d,W,M,headH); s+=rect(M,boardY,boardW,legendY-boardY,"#fff","#000",.35); s+=rect(M,boardY,leftW,topCalH,"#fff","#000",.25); s+=rect(M,boardY,12,topCalH,"#fff","#000",.18); s+=rect(M+12,boardY,66,topCalH,"#fff","#000",.18); s+=rect(M+78,boardY,30,topCalH,"#fff","#000",.18); s+=tx(M+6,boardY+topCalH-2.2,"Regel",1.55,900); s+=tx(M+45,boardY+topCalH-2.2,"Naam",1.55,900); s+=tx(M+93,boardY+topCalH-2.2,"Bouwkundig",1.55,900); s+=drawCalendar(d,chartX,boardY,chartW,topCalH,true); for(let i=0;i<displayN;i++){const y=bodyY+i*rowH, x=d.rows[i]; const phase=x&&isSummary(x.r); s+=rect(M,y,12,rowH,phase?"#63cfc9":i%2?"#eeeeee":"#fff","#000",.13); s+=rect(M+12,y,66,rowH,phase?"#63cfc9":i%2?"#eeeeee":"#fff","#000",.13); s+=rect(M+78,y,30,rowH,phase?"#63cfc9":i%2?"#eeeeee":"#fff","#000",.13); if(x){s+=tx(M+6,y+rowH/2,x.no,1.55,900); s+=tx(M+14+clamp(level(x.r)*2,0,8),y+rowH/2,x.r.name||x.r.title||x.r.id||"—",1.45,phase?900:700,"start"); s+=tx(M+80,y+rowH/2,bouw(x.r,d.s),1.35,phase?900:700,"start");}}
    d.days.forEach((day,i)=>{const x=chartX+i*dayW; if(nonwork(d.s,day))s+=rect(x,bodyY,dayW,bodyH,"#d9d9d9","none",0);});
    for(let i=0;i<=displayN;i++)s+=line(chartX,bodyY+i*rowH,chartX+chartW,bodyY+i*rowH,.09,"#777");
    d.days.forEach((day,i)=>{const x=chartX+i*dayW, dd=dt(day), mon=dd.getUTCDate()===1, week=dd.getUTCDay()===1; s+=line(x,bodyY,x,bodyY+bodyH,mon?.45:week?.28:.08,mon||week?"#000":"#777",mon||week?"":"1 1");}); s+=line(chartX+chartW,bodyY,chartX+chartW,bodyY+bodyH,.35,"#000");
    d.rows.forEach(x=>{const sc=x.sc; if(!sc?.start||!sc?.end)return; const a=clamp(dif(d.range.start,sc.start),0,d.days.length-1), b=clamp(dif(d.range.start,sc.end),0,d.days.length-1), bx=chartX+a*dayW, bw=Math.max(dayW,(b-a+1)*dayW), y=bodyY+x.i*rowH; if(isSummary(x.r)){s+=line(bx,y+rowH*.52,bx+bw,y+rowH*.52,.9,"#000"); s+=tx(bx+bw+1,y+rowH*.5,x.r.name||"Fase",1.45,900,"start");}else{const h=Math.min(3.7,Math.max(2.4,rowH*.58)), by=y+(rowH-h)/2; s+=`<rect x="${bx}" y="${by}" width="${bw}" height="${h}" rx="0.5" fill="${color(x.r,x.i)}" stroke="#000" stroke-width="0.32"/>`; if(bw>7)s+=tx(bx+.8,by+h/2,`${x.no} ${x.r.name||"Taak"}`,1.25,900,"start");}});
    s+=rect(M,botCalY,leftW,bottomCalH,"#fff","#000",.25); s+=tx(M+3,botCalY+6,"Regel",1.4,900,"start"); s+=tx(M+13,botCalY+6,"Naam",1.4,900,"start"); s+=tx(M+25,botCalY+6,"Bouwkundig",1.4,900,"start"); s+=drawCalendar(d,chartX,botCalY,chartW,bottomCalH,false); s+=rect(M,legendY,boardW,legendH,"#fff","#000",.35); s+=tx(M+3,legendY+7,"Bouwkundig",1.65,900,"start"); const lx=M+32, gap=31; LEG.forEach((lab,i)=>{const col=i%6,row=Math.floor(i/6), xx=lx+col*gap, yy=legendY+4+row*5; s+=rect(xx,yy,10,2.4,LEG_COL[i],"#000",.18); s+=tx(xx+12,yy+1.2,lab,1.25,700,"start");}); return s+`</svg>`;}
  function html(d){return `<!doctype html><html lang="nl"><head><meta charset="utf-8"><title>${esc(title(d.p))} - BWS A3</title><style>@page{size:A3 landscape;margin:6mm;}html,body{margin:0;padding:0;background:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact;}svg{display:block;width:408mm;height:285mm;}@media screen{body{background:#666;padding:8px}svg{background:#fff;box-shadow:0 8px 22px rgba(0,0,0,.35);}}</style></head><body data-bws-print-ready="${MARKER}">${fullSvg(d)}</body></html>`;}
  function openPrint(){const d=data(), h=html(d); window.__CWS_BWS_PRINT_LAST_HTML__=h; let f=document.getElementById("cwsBwsA3PrintFrame"); if(!f){f=document.createElement("iframe"); f.id="cwsBwsA3PrintFrame"; f.title="BWS A3 afdruk"; f.setAttribute("aria-hidden","true"); f.style.cssText="position:fixed;right:0;bottom:0;width:0;height:0;border:0;opacity:0;pointer-events:none;"; document.body.appendChild(f);} const w=f.contentWindow, doc=f.contentDocument||w?.document; if(!w||!doc)return false; doc.open(); doc.write(h); doc.close(); setTimeout(()=>{try{w.focus(); w.print();}catch(err){console.error(err);}},220); return true;}
  function trigger(t){const e=t?.closest?.("#printBtn,[data-ctx-action='print'],[data-rev-action='print']"); return !!(e&&(e.id==="printBtn"||e.dataset?.ctxAction==="print"||e.dataset?.revAction==="print"));}
  function install(){if(document.__CWS_BWS_PRINT_A3_CLICK_BOUND__===MARKER)return; document.__CWS_BWS_PRINT_A3_CLICK_BOUND__=MARKER; document.addEventListener("click",e=>{if(!trigger(e.target))return; e.preventDefault(); e.stopPropagation(); e.stopImmediatePropagation(); openPrint();},true); window.CWS_BWS_GanttPrintA3={marker:MARKER,open:openPrint,buildPrintModel:data,printDocumentHtml:html,usesPopup:false,fullPageSvg:true};}
  function inject(f){try{const d=f?.contentDocument||f?.contentWindow?.document; if(!d?.head||d.getElementById(SCRIPT_ID)||d.documentElement?.dataset?.cwsBwsPrintA3Renderer===MARKER)return true; const s=d.createElement("script"); s.id=SCRIPT_ID; s.src=SCRIPT_SRC; s.dataset.cwsBwsPrintA3Renderer=MARKER; d.head.appendChild(s); return true;}catch(_){return false;}}
  function bridge(){if(document.getElementById("printBtn"))return install(); const f=document.getElementById("appFrame"); if(!f)return; const go=()=>inject(f); f.addEventListener("load",()=>setTimeout(go,80)); setTimeout(go,80); let n=0,t=setInterval(()=>{if(go()||++n>45)clearInterval(t);},500);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bridge,{once:true}); else bridge();
})();