(function(){
"use strict";
const M="CWS_BWS_A3_FINAL_V144",SRC="/js/core/gantt_print_bws_final.js?v=144",SID="cwsBwsA3FinalScript";
if(window.__CWS_BWS_A3_FINAL__===M)return; window.__CWS_BWS_A3_FINAL__=M;
const months=["Januari","Februari","Maart","April","Mei","Juni","Juli","Augustus","September","Oktober","November","December"];
const leg=["BWS Bouw","Dak- en wandmontage","Staalbouwer","Buitenkozijnen","Installateur W","Dakdekker","Grondwerk/infra","Betonvloer","Uithardingstijd","Trapleverancier","OH-deuren","Dekvloeren"];
const legc=["#0b71bd","#00d169","#302e6e","#8b35c9","#168fb0","#f28c00","#b57a28","#ce2525","#fff","#9e2a2a","#00b050","#ffff00"];
const pal=["#0b71bd","#00d169","#302e6e","#8b35c9","#168fb0","#f28c00","#ce2525","#00b050","#ffff00","#9e2a2a","#b57a28"];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const pad=n=>String(n).padStart(2,"0"), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function D(v){if(v instanceof Date&&isFinite(v))return new Date(Date.UTC(v.getUTCFullYear(),v.getUTCMonth(),v.getUTCDate())); if(!v)return null; const s=String(v).trim().slice(0,10); let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/); if(m)return new Date(Date.UTC(+m[1],+m[2]-1,+m[3])); m=s.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})$/); return m?new Date(Date.UTC(+m[3],+m[2]-1,+m[1])):null;}
function I(v){const d=D(v);return d?`${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`:""} function NL(v){const d=D(v);return d?`${pad(d.getUTCDate())}-${pad(d.getUTCMonth()+1)}-${d.getUTCFullYear()}`:"—"}
function add(v,n){const d=D(v)||new Date();d.setUTCDate(d.getUTCDate()+Number(n||0));return I(d)} function dif(a,b){const x=D(a),y=D(b);return x&&y?Math.round((y-x)/86400000):0}
function ws(v){const d=D(v)||new Date(),w=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-w+1);return I(d)} function we(v){return add(ws(v),6)}
function iw(v){const d=D(v)||new Date(),x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return {y:x.getUTCFullYear(),w:Math.ceil((((x-y)/86400000)+1)/7)}}
function C(){try{return window.CWS||(window.parent&&window.parent!==window&&window.parent.CWS)||null}catch(_){return window.CWS||null}} function S(){return C()?.getState?.()||{}}
function cp(x){try{return JSON.parse(JSON.stringify(x??null))}catch(_){return x}} function ps(s){const by=s?.projects?.byId||{},o=Array.isArray(s?.projects?.order)?s.projects.order:Object.keys(by);return o.map(id=>by[id]).filter(Boolean)}
function pid(s){const p=ps(s),ids=new Set(p.map(x=>String(x.id||""))),a=[document.getElementById("projectSel")?.value,document.getElementById("mobileProjectSel")?.value,s?.ganttV2?.ui?.projectId,p[0]?.id].filter(Boolean).map(String);return a.find(x=>ids.has(x))||p[0]?.id||null}
function gm(id,s){let m=null;try{m=C()?.gantt?.getProjectGantt?.(id)}catch(_){}m=m||s?.ganttV2?.byProject?.[id]||{};m=cp(m)||{};m.rows=Array.isArray(m.rows)?m.rows.filter(Boolean):[];m.sched=m.sched&&typeof m.sched==="object"?m.sched:{};return m}
function ph(r){const t=String(r?.type||r?.kind||"").toLowerCase();return t==="summary"||t==="phase"||t==="fase"||r?.summary===true||r?.isPhase===true} function ind(r){const n=Number(r?.level??r?.indent??0);return isFinite(n)?Math.max(0,n):0}
function cl(a,b){a=I(a);b=I(b);if(a&&!b)b=a;if(b&&!a)a=b;if(a&&b&&dif(a,b)<0){const t=a;a=b;b=t}return a&&b?{s:a,e:b}:null}
function base(p){return I(p?.startDate||p?.start||p?.date)||ws(new Date())}
function dom(r){const id=String(r?.id||"");const b=[...document.querySelectorAll(".bar[data-id]")].find(e=>String(e.dataset?.id||"")===id);let c=cl(b?.dataset?.start,b?.dataset?.end);if(c)return c;const f=document.querySelector("#timeline .tl-cell.day[data-iso]")?.dataset?.iso,dw=parseFloat(getComputedStyle(document.documentElement).getPropertyValue("--dayW"))||0;if(b&&f&&dw>0){const l=parseFloat(b.style.left)||0,w=parseFloat(b.style.width)||0;if(w>0){const a=Math.max(0,Math.round(l/dw)),z=Math.max(a,Math.round((l+w)/dw)-1);return {s:add(f,a),e:add(f,z)}}}return null}
function raw(r,m){const x=m.sched?.[r.id]||{};return dom(r)||cl(x.start||x.startDate||x.from||r.start||r.startDate||r.begin,x.end||x.endDate||x.to||r.end||r.endDate||r.einde)||null}
function dur(r,c,i){const vals=[r?.duration,r?.days,r?.duur,r?.workdays,c?dif(c.s,c.e)+1:0].map(Number).filter(n=>n>0&&n<60);return Math.max(1,Math.round(vals[0]||[4,5,3,4,7,4,5,6,5,4,6,8][i%12]))}
function res(r,s){const rb=s?.resources?.byId||{},x=r?.resourceId?rb[r.resourceId]:null;return x?.name||r?.resourceName||r?.resource||r?.bouwkundig||r?.department||r?.dept||r?.afdeling||"—"}
function dept(r,s){const rb=s?.resources?.byId||{},x=r?.resourceId?rb[r.resourceId]:null;return r?.bouwkundig||r?.discipline||r?.department||r?.dept||r?.afdeling||x?.dept||r?.resource||r?.resourceId||"—"}
function col(r,i,s){const l=String(res(r,s)||"").toLowerCase(),ix=leg.findIndex(x=>l.includes(x.toLowerCase()));return ix>=0?legc[ix]:pal[i%pal.length]}
function nw(s,d){const x=D(d);if(!x)return false;const wd=x.getUTCDay()===0?7:x.getUTCDay();return wd>=6||s?.settings?.calendar?.workweek?.[wd]===false}
function phaseEnds(rows,i){const lv=ind(rows[i]);let e=i;for(let j=i+1;j<rows.length;j++){if(ind(rows[j])<=lv)break;e=j}return e}
function make(){const st=S(),id=pid(st),p=st?.projects?.byId?.[id]||ps(st)[0]||{},m=gm(id,st),rr=m.rows.length?m.rows:[{id:"empty",name:"Geen Gantt-regels beschikbaar",type:"summary"}],raws=new Map();rr.forEach((r,i)=>{const c=raw(r,m);if(c)raws.set(r.id,c)});const task=rr.filter(r=>!ph(r)),starts=task.map(r=>raws.get(r.id)?.s).filter(Boolean),unique=new Set(starts).size,broad=task.filter(r=>{const c=raws.get(r.id);return !c||dif(c.s,c.e)+1>45}).length,bad=unique<=1||broad/Math.max(1,task.length)>.35;let map=new Map(),cur=ws(base(p));rr.forEach((r,i)=>{if(ph(r))return;const c=raws.get(r.id),du=dur(r,c,i);let u=null;if(!bad&&c&&dif(c.s,c.e)+1<=45)u=c;if(!u){const s=add(cur,i?Math.max(1,Math.floor(du*.45)):2);u={s,e:add(s,du-1)};cur=add(s,Math.max(1,Math.floor(du*.75)))}map.set(r.id,u)});for(let i=rr.length-1;i>=0;i--){if(!ph(rr[i]))continue;const kids=rr.slice(i+1,phaseEnds(rr,i)+1).map(r=>map.get(r.id)).filter(Boolean);if(kids.length)map.set(rr[i].id,{s:kids.map(x=>x.s).sort()[0],e:kids.map(x=>x.e).sort().at(-1)})}const ds=[];rr.forEach(r=>{const c=map.get(r.id);if(c){ds.push(c.s,c.e)}});let a=ds.length?ds.slice().sort()[0]:base(p),z=ds.length?ds.slice().sort().at(-1):add(a,70);a=ws(add(a,-7));z=we(add(z,21));if(dif(a,z)+1<84)z=add(a,83);if(dif(a,z)+1>126)z=add(a,125);const days=[];for(let d=a,g=0;g<140&&dif(d,z)<=0;d=add(d,1),g++)days.push(d);return {st,p,m,days,range:{s:a,e:z},rows:rr.map((r,i)=>({r,i,no:i+1,c:map.get(r.id)||{}}))}}
function T(x,y,t,fs=2,w=700,a="middle"){return `<text x="${x}" y="${y}" font-size="${fs}" font-weight="${w}" text-anchor="${a}" dominant-baseline="middle" font-family="Arial,Helvetica,sans-serif">${esc(t)}</text>`} function L(x1,y1,x2,y2,w=.18,c="#000",d=""){return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${c}" stroke-width="${w}"${d?` stroke-dasharray="${d}"`:""}/>`} function R(x,y,w,h,f="#fff",s="#000",sw=.18){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${f}" stroke="${s}" stroke-width="${sw}"/>`}
function seg(days,t){const key=d=>{const x=D(d);if(t==="y")return String(x.getUTCFullYear());if(t==="m")return `${x.getUTCFullYear()}-${pad(x.getUTCMonth()+1)}`;if(t==="w"){const q=iw(x);return `${q.y}-W${pad(q.w)}`}return d},lab=k=>t==="y"?k:t==="m"?months[+k.split("-")[1]-1]:t==="w"?String(+(k.match(/W(\d+)$/)||[])[1]||""):pad(D(k).getUTCDate());const o=[];days.forEach(d=>{const k=key(d),l=o.at(-1);if(l&&l.k===k)l.n++;else o.push({k,n:1,l:lab(k)})});return o}
function cal(d,x,y,w,top){const ord=top?["y","m","d","w"]:["w","d","m","y"],hs=top?[4.4,5,4.8,4.8]:[4.8,4.8,5,4.4];let s="",yy=y,dw=w/d.days.length;ord.forEach((t,i)=>{const h=hs[i];if(t==="d")d.days.forEach((day,j)=>{const xx=x+j*dw;s+=R(xx,yy,dw,h,nw(d.st,day)?"#d9d9d9":"#fff","#333",.08)+T(xx+dw/2,yy+h/2,pad(D(day).getUTCDate()),1.12,800)});else{let xx=x;seg(d.days,t).forEach(g=>{const ww=g.n*dw;s+=R(xx,yy,ww,h,"#fff","#111",.13)+T(xx+ww/2,yy+h/2,g.l,t==="w"?1.22:1.52,900);xx+=ww})}yy+=h});return s}
function page(d){const W=408,H=285,M=3.2,HH=23,LH=15,BY=M+HH,BW=W-2*M,LW=106,CX=M+LW,CW=BW-LW,TCH=19,BCH=19,LY=H-M-LH,BCY=LY-BCH,BODY=BY+TCH,BH=BCY-BODY,N=Math.max(45,d.rows.length),RH=BH/N,DW=CW/d.days.length,p=d.p;let s=`<svg xmlns="http://www.w3.org/2000/svg" width="408mm" height="285mm" viewBox="0 0 408 285" shape-rendering="crispEdges">`;
s+=R(M,M,W-2*M,H-2*M,"#fff","#000",.55)+R(M,M,W-2*M,HH,"#fff","#000",.35)+R(M,M,78,HH,"#fff","#000",.25);const logo=d.st?.company?.logo?.dataUrl||C()?.getCompanyLogo?.()||"";s+=logo?`<image href="${esc(logo)}" x="${M+6}" y="${M+4}" width="64" height="14" preserveAspectRatio="xMidYMid meet"/>`:R(M+6,M+4,64,14,"#ffd92f","none",0)+T(M+38,M+10,"TASCHE",5.5,900)+T(M+38,M+15,"STAALBOUW",2.4,800);s+=T(W/2,M+8,p?.name||p?.title||"Project",3.2,900)+T(W/2,M+13,`Opdrachtg.: ${p?.client||p?.opdrachtgever||"—"}`,2.35,900)+T(W/2,M+17,`Bouwplanning · bereik ${NL(d.range.s)} t/m ${NL(d.range.e)}`,1.55,700);[["Project nr.:",p?.nr||p?.code||p?.id||"—"],["Opdrachtg.:",p?.client||p?.opdrachtgever||"—"],["Omschrijving:",p?.omschrijving||p?.description||p?.name||"—"],["Projectleider:",p?.projectleider||d.st?.user?.name||"—"],["Plotdatum:",new Date().toLocaleDateString("nl-NL")],["Revisienr.:",p?.revision||"—"],["Revisiedatum:",p?.revisionDate?NL(p.revisionDate):"—"]].forEach((r,i)=>{const x=W-M-84,rh=HH/7,y=M+i*rh;s+=R(x,y,28,rh,"#fff","#000",.16)+R(x+28,y,56,rh,"#fff","#000",.16)+T(x+1.3,y+rh/2,r[0],1.2,900,"start")+T(x+30,y+rh/2,r[1],1.2,700,"start")});
s+=R(M,BY,BW,LY-BY,"#fff","#000",.35)+R(M,BY,LW,TCH,"#fff","#000",.25)+R(M,BY,12,TCH,"#fff","#000",.18)+R(M+12,BY,64,TCH,"#fff","#000",.18)+R(M+76,BY,30,TCH,"#fff","#000",.18)+T(M+6,BY+TCH-2.2,"Regel",1.52,900)+T(M+44,BY+TCH-2.2,"Naam",1.52,900)+T(M+91,BY+TCH-2.2,"Bouwkundig",1.52,900)+cal(d,CX,BY,CW,true);
for(let i=0;i<N;i++){const y=BODY+i*RH,row=d.rows[i],phs=row&&ph(row.r),fill=phs?"#63cfc9":i%2?"#eee":"#fff";s+=R(M,y,12,RH,fill,"#000",.13)+R(M+12,y,64,RH,fill,"#000",.13)+R(M+76,y,30,RH,fill,"#000",.13);if(row)s+=T(M+6,y+RH/2,row.no,1.45,900)+T(M+14+clamp(ind(row.r)*2,0,8),y+RH/2,row.r.name||row.r.title||row.r.id||"—",1.38,phs?900:700,"start")+T(M+78,y+RH/2,dept(row.r,d.st),1.28,phs?900:700,"start")}
d.days.forEach((day,i)=>{const x=CX+i*DW;if(nw(d.st,day))s+=R(x,BODY,DW,BH,"#d9d9d9","none",0)});for(let i=0;i<=N;i++)s+=L(CX,BODY+i*RH,CX+CW,BODY+i*RH,.09,"#777");d.days.forEach((day,i)=>{const x=CX+i*DW,dd=D(day),mo=dd&&dd.getUTCDate()===1,we=dd&&dd.getUTCDay()===1;s+=L(x,BODY,x,BODY+BH,mo?.45:(we?.28:.08),mo||we?"#000":"#777",mo||we?"":"1 1")});s+=L(CX+CW,BODY,CX+CW,BODY+BH,.35,"#000");d.rows.forEach(row=>{const c=row.c;if(!c.s||!c.e)return;const a=clamp(dif(d.range.s,c.s),0,d.days.length-1),b=clamp(dif(d.range.s,c.e),0,d.days.length-1),x=CX+a*DW,w=Math.max(DW,(b-a+1)*DW),y=BODY+row.i*RH;if(ph(row.r))s+=L(x,y+RH*.52,x+w,y+RH*.52,.9,"#000")+T(x+w+1,y+RH*.5,row.r.name||"Fase",1.35,900,"start");else{const bh=Math.min(3.7,Math.max(2.3,RH*.6)),by=y+(RH-bh)/2;s+=`<rect x="${x}" y="${by}" width="${w}" height="${bh}" rx="0.5" fill="${col(row.r,row.i,d.st)}" stroke="#000" stroke-width="0.32"/>`;if(w>6)s+=T(x+.8,by+bh/2,`${row.no} ${row.r.name||"Taak"}`,1.16,900,"start")}});s+=R(M,BCY,LW,BCH,"#fff","#000",.25)+T(M+3,BCY+6,"Regel",1.35,900,"start")+T(M+13,BCY+6,"Naam",1.35,900,"start")+T(M+25,BCY+6,"Bouwkundig",1.35,900,"start")+cal(d,CX,BCY,CW,false)+R(M,LY,BW,LH,"#fff","#000",.35)+T(M+3,LY+7,"Bouwkundig",1.55,900,"start");leg.forEach((l,i)=>{const x=M+32+(i%6)*31,y=LY+4+Math.floor(i/6)*5;s+=R(x,y,10,2.4,legc[i],"#000",.18)+T(x+12,y+1.2,l,1.2,700,"start")});return s+`</svg>`}
function html(d){return `<!doctype html><html lang="nl"><head><meta charset="utf-8"><title>BWS A3</title><style>@page{size:A3 landscape;margin:6mm}html,body{margin:0;padding:0;background:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}svg{display:block;width:408mm;height:285mm}@media screen{body{background:#666;padding:8px}svg{background:#fff;box-shadow:0 8px 22px rgba(0,0,0,.35)}}</style></head><body data-bws-print-ready="${M}">${page(d)}</body></html>`}
function open(){const d=make(),h=html(d);window.__CWS_BWS_PRINT_LAST_HTML__=h;let f=document.getElementById("cwsBwsA3PrintFrame");if(!f){f=document.createElement("iframe");f.id="cwsBwsA3PrintFrame";f.style.cssText="position:fixed;right:0;bottom:0;width:0;height:0;border:0;opacity:0;pointer-events:none";document.body.appendChild(f)}const w=f.contentWindow,doc=f.contentDocument||w?.document;if(!w||!doc)return false;doc.open();doc.write(h);doc.close();setTimeout(()=>{try{w.focus();w.print()}catch(e){console.error(e)}},220);return true}
function install(){if(document.__CWS_BWS_A3_FINAL_BOUND__===M)return;document.__CWS_BWS_A3_FINAL_BOUND__=M;document.addEventListener("click",e=>{const b=e.target?.closest?.("#printBtn,[data-ctx-action='print'],[data-rev-action='print']");if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open()},true);window.CWS_BWS_GanttPrintA3={marker:M,open,buildPrintModel:make,usesPopup:false,finalBws:true}}
function inject(fr){try{const d=fr?.contentDocument||fr?.contentWindow?.document;if(!d?.head)return false;let old=d.getElementById(SID);if(old&&String(old.src||"").includes("v=144"))return true;if(old)old.remove();const s=d.createElement("script");s.id=SID;s.src=SRC;s.dataset.cwsMarker=M;d.head.appendChild(s);return true}catch(_){return false}}
function boot(){if(document.getElementById("printBtn"))return install();const fr=document.getElementById("appFrame");if(!fr)return;const go=()=>inject(fr);fr.addEventListener("load",()=>setTimeout(go,80));setTimeout(go,80);let n=0,t=setInterval(()=>{if(go()||++n>80)clearInterval(t)},300)}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot,{once:true}):boot();
})();